# Generated by Django 5.1.7 on 2025-03-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
