# Generated by Django 5.1.7 on 2025-03-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
