# Generated by Django 5.1.7 on 2025-03-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_created_at_remove_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
