# Generated by Django 5.1.7 on 2025-03-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_created_at_comment_post_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
