# Generated by Django 5.1.7 on 2025-03-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageSrc',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics/'),
        ),
    ]
