# Generated by Django 5.1.7 on 2025-03-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_imagesrc_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='static/img/profile_picture.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
