# Generated by Django 5.1.7 on 2025-03-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='profile_pics'),
        ),
    ]
